# ===== Тема и плагины =====
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# ===== Внешний вид =====
minimal_mistakes_skin: "dark"
show_date: false
# Включение поиска
search: true

reading_time: true
words_per_minute: 200
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true   # Включаем отображение времени чтения

# Настройка поискового провайдера (по умолчанию используется lunr.js)
search_provider: lunr  # lunr, algolia, google-custom

# ===== Навигация (перенесено в _data/navigation.yml) =====

# ===== Основная информация =====
title: Название сайта
# description: >-
#   Блог о путешествиях. Здесь я делюсь впечатлениями, фотографиями и 
#   полезными советами для самостоятельных путешествий.

# author:
#   name: "Ваше Имя"
#   email: "your-email@example.com"

# ===== Настройки обработки =====
markdown: kramdown
highlighter: rouge
permalink: pretty

locale: "ru-RU"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/mcei/travel

# ===== Исключения при сборке =====
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - cmds.txt
