remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - title: The blog repo
      icon: github
      url: "https://github.com/mcei/travel"

# Остальные настройки
title: Название сайта
description: Сайт о путешествиях
markdown: kramdown
highlighter: rouge

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - cmds.txt

permalink: pretty